# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/bookit',
                'doc_host': 'https://1iis.github.io',
                'git_url': 'https://github.com/1iis/bookit',
                'lib_path': 'bookit'},
  'syms': {'bookit.core': {'bookit.core.foo': ('core.html#foo', 'bookit/core.py')}}}
