"""Fill in a module description here

Docs: https://1iis.github.io/bookitcore.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['foo']

# %% ../nbs/00_core.ipynb #8220856d
def foo(): pass
